const data = {
  products : [
    {
      _id:'1',
      name : 'Creveți sălbatici Carabineros 1kg',
      slug : 'Creveți sălbatici Carabineros 1kg',
      category : 'Fructe de mare',
      image : '/images/creveti2-carabineros.jpg',
      price : 1000,
      countInStock : 1,
      brand : 'Alfredo',
      rating : 4.5 ,
      numReviews : 10 ,
      description : 'Creveți sălbatici Carabineros 1kg'
    },
    {
      _id:'2',
      name : 'Prajitura Choco Pie cu cacao LOTTE (12 x 28g) 336g',
      slug : 'Prajitura Choco Pie cu cacao LOTTE (12 x 28g) 336g',
      category : 'Noodles si noodles instant',
      image : '/images/prajitura-choco-pie-cu-cacao-lotte-12-x-28g.jpg',
      price : 32,
      countInStock : 10,
      brand : 'Lotte',
      rating : 4.5 ,
      numReviews : 10 ,
      description : 'Prajitura Choco Pie cu cacao LOTTE (12 x 28g) 336g'
    },
    {
      _id:'3',
      name : 'Taitei din grau (ramen noodles) ADOMI 500g',
      slug : 'Taitei din grau (ramen noodles) ADOMI 500g',
      category : 'Noodles si noodles instant',
      image : '/images/taiteiDinGrauRamenNoodlesAdomi.jpg',
      price : 12 ,
      countInStock : 11,
      brand : 'Adomi',
      rating : 4.5 ,
      numReviews : 10 ,
      description : 'Taitei din grau (ramen noodles) ADOMI 500g'
    },
    {
      _id:'4',
      name : 'Lotte Snow Almond Pepero 32g',
      slug : 'Lotte Snow Almond Pepero 32g',
      category : 'Noodles si noodles instant',
      image : '/images/lotte-snow-almond-pepero-32g.jpg',
      price : 8.50,
      countInStock : 10,
      brand : 'Lotte',
      rating : 4.5 ,
      numReviews : 10 ,
      description : 'Lotte Snow Almond Pepero 32g'
    },
    {
      _id:'5',
      name : 'Supa instant Extra Spicy Yeol Ramen OTT 120g',
      slug : 'Supa instant Extra Spicy Yeol Ramen OTT 120g',
      category : 'Noodles si noodles instant',
      image : '/images/supaInstantExtraSpicyYeolRamenOtt.jpg',
      price : 12.50,
      countInStock : 15,
      brand : 'Ottogi',
      rating : 4.5 ,
      numReviews : 10 ,
      description : 'Supa instant Extra Spicy Yeol Ramen OTT 120g'
    },
    {
      _id:'6',
      name : 'Taitei spicy sesame Obento 240g',
      slug : 'Taitei spicy sesame Obento 240g',
      category : 'Noodles si noodles instant',
      image : '/images/taitei-spicy-sesame-obento-240g.png',
      price : 15,
      countInStock : 18,
      brand : 'Obento',
      rating : 4.5 ,
      numReviews : 10 ,
      description : 'Taitei spicy sesame Obento 240g'
    },
    {
      _id:'7',
      name : 'Mochi asortate YL 450g',
      slug : 'Mochi asortate YL 450g',
      category : 'Noodles si noodles instant',
      image : '/images/mochi-asortate-yl-450g.jpg',
      price : 39.50,
      countInStock : 10,
      brand : 'Lotte',
      rating : 4.5 ,
      numReviews : 10 ,
      description : 'Mochi asortate YL 450g'
    },
    {
      _id:'8',
      name : 'Pasta de creveti MAE PRANOM 100g',
      slug : 'Pasta de creveti MAE PRANOM 100g',
      category : 'Noodles si noodles instant',
      image : '/images/pasta-de-creveti-mae-pranom-100g.jpg',
      price : 18 ,
      countInStock : 10,
      brand : 'MAE PRANOM',
      rating : 4.5 ,
      numReviews : 10 ,
      description : 'Pasta de creveti MAE PRANOM 100g'
    },
    {
      _id:'9',
      name : 'Alge nori KC 2gx10 buc',
      slug : 'Alge nori KC 2gx10 buc',
      category : 'Noodles si noodles instant',
      image : '/images/alge-nori-kc-2gx10-buc.jpg',
      price : 14,
      countInStock : 10,
      brand : 'Seasoned',
      rating : 4.5 ,
      numReviews : 10 ,
      description : 'Alge nori KC 2gx10 buc'
    },
  ],
};
export default data ;